project_id = "gcjaeoxjhcfeispehmga"

[functions.signature-portal]
verify_jwt = false

[functions.landing-capture]
verify_jwt = false

[functions.wavoip-webhook]
verify_jwt = false

[functions.wavoip-webhook-config]
verify_jwt = false

[functions.wavoip-event-reprocess]
verify_jwt = true
